"""Pydantic schemas for API request/response validation."""

from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime


# ─── Document ───

class DocumentResponse(BaseModel):
    id: str
    name: str
    created_at: datetime
    version_count: int = 0

    model_config = {"from_attributes": True}


class DocumentVersionResponse(BaseModel):
    id: str
    document_id: str
    version_number: int
    file_hash: str
    filename: str
    ingested_at: datetime

    model_config = {"from_attributes": True}


# ─── Node ───

class NodeSummary(BaseModel):
    """Lightweight node representation for tree listings."""
    id: str
    heading: str
    level: int
    node_path: str
    has_children: bool = False
    content_hash: str

    model_config = {"from_attributes": True}


class NodeDetail(BaseModel):
    """Full node with body text and children."""
    id: str
    heading: str
    level: int
    body_text: str
    content_hash: str
    node_path: str
    parent_id: Optional[str] = None
    position: int
    version_id: str
    matched_node_id: Optional[str] = None
    has_changed: bool = False
    children: list["NodeSummary"] = []

    model_config = {"from_attributes": True}


# ─── Diff ───

class DiffResult(BaseModel):
    """Result of comparing a node across versions."""
    node_id: str
    heading: str
    changed: bool
    from_version: int
    to_version: int
    insertions: int = 0
    deletions: int = 0
    modified_lines: list[str] = []
    summary: str = ""


# ─── Selection ───

class SelectionItemCreate(BaseModel):
    node_id: str
    version_id: str


class SelectionCreate(BaseModel):
    name: str
    items: list[SelectionItemCreate]


class SelectionItemResponse(BaseModel):
    id: str
    node_id: str
    version_id: str
    content_hash_at_selection: str
    heading: Optional[str] = None
    body_text: Optional[str] = None

    model_config = {"from_attributes": True}


class SelectionResponse(BaseModel):
    id: str
    name: str
    created_at: datetime
    items: list[SelectionItemResponse] = []

    model_config = {"from_attributes": True}


# ─── Search ───

class SearchResult(BaseModel):
    node_id: str
    heading: str
    node_path: str
    level: int
    snippet: str = ""
    version_id: str


class SearchResponse(BaseModel):
    query: str
    version: Optional[int] = None
    results: list[SearchResult] = []
    total: int = 0


# ─── Generation (LLM) ───

class TestCaseSchema(BaseModel):
    """A single QA test case generated by the LLM."""
    id: str = ""
    title: str
    preconditions: str = ""
    steps: list[str] = []
    expected_result: str
    traceability_ref: str = ""  # Links back to the source node


class GenerationRequest(BaseModel):
    selection_id: str


class GenerationResponse(BaseModel):
    id: str
    selection_id: str
    model: str
    prompt_version: str
    test_cases: list[TestCaseSchema] = []
    created_at: str
    staleness_status: Optional[str] = None  # CURRENT, STALE, ORPHANED
    stale_nodes: list[str] = []


# ─── Staleness ───

class NodeStalenessInfo(BaseModel):
    node_id: str
    heading: str
    status: str  # CURRENT, STALE, ORPHANED
    old_hash: str
    current_hash: Optional[str] = None


class StalenessResponse(BaseModel):
    generation_id: str
    overall_status: str  # CURRENT, STALE, PARTIALLY_STALE, ORPHANED
    nodes: list[NodeStalenessInfo] = []
